### ISSUE TITLE
Error on home page  

### ISSUE THREAD

**Issue by abhijitgujar86** [AnalyticalGraphicsInc/3d-tiles-samples#25]
I cloned the repo , ran npm install and start . the home page is showing error 
"Cannot GET /tilesets/"

**Comment by lilleyse** [comment]
The tilesets are hosted at that address but you need to be running Cesium separately in order to load the tilesets. If you have a Cesium app running you should be able to paste the sample code from the instructions and it will work.

**Comment by abhijitgujar86** [comment]
Thanks for help. Great work guys. Thanks to all.
