### ISSUE TITLE
How to build 3D tiles

### ISSUE THREAD

**Issue by gitzhang** [AnalyticalGraphicsInc/3d-tiles-samples#7]
Hi pjcozzi.
How to build 3d tiles from my shapefile?

**Comment by lilleyse** [comment]
I'm not aware of any converts for shapefile to 3D Tiles. The vector tile format is still a [work-in-progress](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/TileFormats/VectorData), so check back in a little bit.
