### ISSUE TITLE
Update samples to latest 3D Tiles spec

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/3d-tiles-samples#9]
* [ ] Prefix BATCHID semantic with an underscore, https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/160

Also update the tilesets in https://github.com/AnalyticalGraphicsInc/cesium/tree/3d-tiles/Specs/Data/Cesium3DTiles

**Comment by pjcozzi** [comment]
Let's not do this right away so we can batch up other changes like updating to glTF 1.1.

**Comment by foobarbecue** [comment]
I'm a beginner trying to jump in to using 3D tiles and have wasted most of a weekend trying to figure out what's what. I guess this thread means that the examples here don't work with latest cesium -- if that's the case, please at least add a note in the readme saying what versions it works with to keep from people like me wasting our time and if there are any up to date examples anywhere. I understand that this is under rapid development and I think that's great but please consider people like me who will waste time trying to make this work.

**Comment by lilleyse** [comment]
The samples here do work fine in Cesium. There's just that minor fix needed above, but Cesium allows both `BATCHID` and `_BATCHID` at the moment.

Now that the [3d-tiles-generator](https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/tree/master/generator) project is in I plan on updating these tilesets very soon.

**Comment by foobarbecue** [comment]
Oh ok, sorry and thanks for the quick response!

**Comment by lilleyse** [comment]
Fixed in https://github.com/AnalyticalGraphicsInc/3d-tiles-samples/pull/10
